#!/bin/zsh

echo -e "\e[1;96m                                                                                                        "
echo -e "\e[1;96m                                                                          .;clc,                        "
echo -e "\e[1;96m                                                                         lXXXXXXK;                      "
echo -e "\e[1;96m                                                                        .XXXXXXXXX                      "
echo -e "\e[1;96m                                                                         OXXXXXXXd                      "
echo -e "\e[1;96m                                                                          :xO0Od'                .      "
echo -e "\e[1;96m                                                           ;llc'                              .xXXXk.   "
echo -e "\e[1;96m                                                         .KXXXXXk                 xd   cl.    cXXXXXd   "
echo -e "\e[1;96m                  .,;.   ,;;                             dXXXXXXX,         .ckK:  ..  kXXl     lOK0o.   "
echo -e "\e[1;96m        okkO:     kXX.  :XXd                ';:;,.    .lOXXXXXXXXXkc     .dXXXXXOl:cdKXXXXk'            "
echo -e "\e[1;96m       xX0KX0     XXK   xXX,      ...    ,kXX0kkO0k:;dXKKXXKOOXXXKOkk;  .KXKKXXXXKKKXXXXKKXXd;,         "
echo -e "\e[1;96m      xXK.xXX.   :XXd   XXK   .o0X00XXk.cXx,   .  .cXXO  ':  .Xo.       OXc  :XX:   XXK. .XXXXXK;       "
echo -e "\e[1;96m     oXX; cXXl   OXX,  'XXx  .KX0.  kXXoX;  'OXXc  lXXc   'od0,  c0XK.  cXd  ;Xk .  0X'  OXXXXXXl  ,;.  "
echo -e "\e[1;96m    cXXx..cXX0  .XXX   lXX;  0XXo:oOX0o.d   KXXX.  0XX.  ,XXXo  .XXXX,  ;XO  ,K. O. Oo  lXXXXlc.  xXXX; "
echo -e "\e[1;96m   ;XXXKKKKXXX. ;XXO   0XX.  XXXl:;'.  l:  .XXXk  .XXK   0XXX,  :XXX0   xXK  ,; lX' d  .XXXXx     .ooc  "
echo -e "\e[1;96m  ,XXO     0XXc oXXO,  XXX:  dXXx;,:dd XO   ;:'   :XXd  .XXXXk   ldl.  dXXX  . .XX,    0XOc;.           "
echo -e "\e[1;96m  ooo.     :ooc .okkd  :xkx.  ,oxkkdl, 0X0l;;cx.  kXXd,,dXXKOK0c,..';oKXXXXc,''OXXd,,,kX0     ...       "
echo -e "\e[1;96m                                       'Ocdkkx,  ,XXXXXXX0;...kXXXKXXXXXXXXd.  .OXXXXKko'   lKXXXKo     "
echo -e "\e[1;96m                                          .   .,dXXXKl;;. 'XXK.'.  .;oxkkxd   .. ...       xXXXXXXXd    "
echo -e "\e[1;96m                                          .;okOOkxl'  dx..';c'              ,0XXK;         lXXXXXXXc    "
echo -e "\e[1;96m                                                         ',                 cXXXXo          'dO0Od,     "
echo -e "\e[1;96m                                                                             .;;.                       "
echo -e "\e[1;96m                                                                                                        "
echo -e "\e[1;96m  "
echo -e "\e[1;96m  "