#!/bin/zsh

echo -e "\e[1;96m                                                                                                                  c0WMWKo"
echo -e "\e[1;96m                                                                                                                xWMMMMMMMWk"
echo -e "\e[1;96m                                                                                                               NMMMMMMMMMMMW"
echo -e "\e[1;96m                                                                                                              ;MMMMMMMMMMMMMd"
echo -e "\e[1;96m                                                                                                              .MMMMMMMMMMMMM'"
echo -e "\e[1;96m                                                                                                               .MMMMMMMMMMM,"
echo -e "\e[1;96m                                                                                                                  0MMMMMK"
echo -e "\e[1;96m                                                                                                                                                  cdLLl,"
echo -e "\e[1;96m                                                                                         :x0KK0d,                                               lMMMMMMM0"
echo -e "\e[1;96m                                                                                       'NMMMMMMMMK                          .xd.     ,,         MMMMMMMMM,"
echo -e "\e[1;96m                                                                                       MMMMMMMMMMMN                   ,,     XO    .MMMW        lMMMMMMMX"
echo -e "\e[1;96m                           Llio.     Lioc                                             .MMMMMMMMMMMM                :OWMM0          KMMMM.         .MMMl"
echo -e "\e[1;96m           ,loodxl        ,MMMM.    cMMMM                                           :xWMMMMMMMMMMMMNd;           dNMMMMMMNd,.  .;xWMMMMMMk."
echo -e "\e[1;96m          ;MMMMMMM        KMMMM     XMMMK                       .ckKNMMWX0o,     .OMMMMMMMMMMMMMMMMMMMWd       ;WMMMMMMMMMMMMMMMMMMMMMMMMMMx"
echo -e "\e[1;96m         .MMM,XMMM.       MMMMO     MMMM:                     ,KMMMMMWolOMMMNd:ckMMMMMMMMMMNOMMMMMMMMXldNo    cMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl;,."
echo -e "\e[1;96m        .WMMo lMMMd      .MMMM,    'MMMM       ,o0NMMMMN0l   xMMW             xMMMN    N:    .MMk            .MMM    .MMMM:     MMMM'    MMMMMMMMX'"
echo -e "\e[1;96m       .WMMN  .MMMW      cMMMM     OMMMN     ;XMMM:   xMMMW.;MW      .,,,     XMMMl          KN      .,,     'MMM     MMMk      MMMk    lMMMMMMMMMM"
echo -e "\e[1;96m       NMMM    MMMM.     XMMMK     MMMMd    oMMMM     ;MMMM'KW     lWMMMM     MMMM.      lkk0W     oWMMMX     0MM.    MMM   .   MMM    .MMMMMMMMMM0    .i."
echo -e "\e[1;96m      XMMM.    NMMMd     MMMM:    .MMMM.   .MMMM.   .lWMMMc 0.    lMMMMMO    ,MMMM     ,WMMMM.    cMMMMMM     xMM,    MM'  .k   NMc    NMMMMMMMMW     KMMMWo"
echo -e "\e[1;96m     XMMMMl;;;;WMMMM    ;MMMM     xMMMM    XMMMM00XWMMM.    X     MMMMMM'    KMMMx    .MMMMMW     MMMMMMW     NMMo    Mo   XW   K0    KMMMMMM.       .MMMMMK"
echo -e "\e[1;96m    KMMMMMMMMMMMMMMM.   KMMMN     MMMMX    MMMMN           OO     MMMMMW     MMMM'    dMMMMMW     MMMMMM,    .MMMK    K   lMM   x    cMMMMMMM         'MMMW'"
echo -e "\e[1;96m   0MMMK       .MMMMl   MMMMd    .MMMMc    oMMMM.      ,  .MM     'MMX      'MMMM     WMMMMMM     oMMMM.     NMMMM       .MMM   .   .MMMMMMM."
echo -e "\e[1;96m  kMMMM         MMMMW   MMMMWk;  .MMMMNk.   oMMMMOddd0WMX.,MMO              OMMMW    .MMMMMMMK             :WMMMMM       NMMM       NMMW"
echo -e "\e[1;96m :OOOO.         kOOOO    xMMMMN    KMMMMk      NMMMMMM,   .MMMXc'.  .:O     MMMM0    oMMMMMMMMNl.       .cKMMMMMMM,     dMMMM'     dMMM"
echo -e "\e[1;96m                                                           kMMMMMMMMMMl    :MMMMMMMMMMMMW    .MMMWK000XWMMMMMMMMMMMx     MMMMMMMMMMMMMX      .cxO0Odc"
echo -e "\e[1;96m                                                            x             .WMMMMMMMMMMX   ..  'MMMMMMMMMMMMMMMMMMM:       :MMMMMMMN         OMMMMMMMMWd"
echo -e "\e[1;96m                                                                         oMMMMMMW        XMMMO          :MMMMMMMMM                         WMMMMMMMMMMMK"
echo -e "\e[1;96m                                                                ,c;:coxKMMMMMM,  .0Kk    OMMMc                       ,oxxo;                MMMMMMMMMMMMM"
echo -e "\e[1;96m                                                                      :l.              :,                           0MMMMMMX               :MMMMMMMMMMM."
echo -e "\e[1;96m                                                                                                                    WMMMMMMM                 oMMMMMMM:"
echo -e "\e[1;96m                                                                                                                     oMMMMK           "
echo -e "\e[1;96m                                                                                                                       '''            "
echo -e "\e[1;96m  "
echo -e "\e[1;96m  "
